### PR TITLE
Allow Prettier options to be configurable in Atom settings

### PR DESCRIPTION
**Pull request by skevy**
Really wanted to use this, but needed Prettier options to be configurable! :)

Thanks for making this, Kent!

### CODE REVIEW

**Comment by kentcdodds** [comment]
This looks ok to me. Could you post a screenshot of what the settings page looks like?

Also, I hesitate to add this because I feel like it should be unnecessary. `prettier-eslint` should derive the prettier-options via the eslint config which it finds for your file. But I'm open to hearing use cases! :) I'm guessing this'll be merged.

**Comment by skevy** [comment]
@kentcdodds here's a screenshot:

Image

**Comment by skevy** [comment]
@kentcdodds So re: inferring the options -- you're saying that it would look at my ESLint config, see what i have set for the line width rule, tab width rule, quote rule, etc and then set the Prettier settings accordingly? That seems reasonable and pretty neat. Hadn't thought about that...but maybe if I get a minute later today I can make that happen instead.

We would still need the "Use Flow Parser" option, if people want that (unless we want to force people to use Babylon with this plugin, which may be fine).

**Review by kentcdodds — APPROVED** [review]
I think I'm good with this.. @robwise, do you have any feedback?

**Comment by kentcdodds** [comment]
Oh, and do you wanna [add yourself to the contributors table](https://github.com/kentcdodds/prettier-eslint-atom/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)?

**Comment by skevy** [comment]
@kentcdodds yep, added! :)

**Comment by robwise** [comment]
I would definitely opt for having prettier options be pulled in from eslint. I don't get why you'd want to set Prettier's `trailingCommas` option, for example, to be different from eslint, because eslint is going to automatically change it back instantly anyway? The only exception would be the `useFlowParser` option.

**Comment by skevy** [comment]
@robwise Ok. I'll just build that functionality then. Disregard this PR for now.

**Comment by kentcdodds** [comment]
This package has been deprecated. Please see the README for instructions on moving to the new plugin.

**Pull request closed without merging**
